### ISSUE TITLE
[Session] 意図しないタイミングでInterruptが送られてきがち  

### ISSUE THREAD

**Issue by p1ass** [camphor-/relaym-server#119]
## 概要

 意図しないタイミングでInterruptが送られてくることがある

## 再現方法

いまいち分かってない。

全ての再生が終わった後に、追加で曲を追加するとINTERRUPT送られてくる匂いを感じている。

その他のパターンもありそう

## ログ

```
```

## 対処方法

- [ ] Task1

**Comment by p1ass** [comment]
Spotifyで次の曲の再生が始まる〜トリガーの処理が終わる間にGET /sesisons/:id を叩くとINTERRUPTになるっぽい 😇

<img width="1015" alt="スクリーンショット 2020-07-22 15 20 29" src="https://user-images.githubusercontent.com/30015728/88141630-ee7db880-cc2e-11ea-9afb-00f49df3d15d.png">

**Comment by p1ass** [comment]
これ対応するの面倒くさ！

**Comment by sanposhiho** [comment]
処理中みたいなstateを作って処理の間はそれに変更しておく&イベントで処理中的な物を返すみたいな…？（~クソめんどくさい~

**Comment by p1ass** [comment]
トリガーがExpireする前に曲が先に進んでしまうのが問題だから、処理中のstateを作っても上手いことハンドリングできなくない？

**Comment by p1ass** [comment]
いやでも出来るか

ここで待ってる7秒のせいでバグってるから、time.Sleepする前にstateかなにかを書き換えれて条件分岐すれば良い気が数r

https://github.com/camphor-/relaym-server/blob/master/usecase/session_timer.go#L34
