### ISSUE TITLE
意図しないメンバーによってSpotifyが乗っ取られるのを防ぐ

### ISSUE THREAD

**Issue by dora1998** [camphor-/relaym-server#122]
## 概要

現状の仕組みだと、セッションのURLさえわかれば誰でも作成者のSpotifyを乗っとれてしまう。
使用後のURLがいつまでも有効なため、これは運用が長期に渡るほど問題になるので、対策を考えたい。

## 要件
- セッション作成者が好きなタイミングでセッションを無効にできる
- セッション使用後放置してても、セッションが無効になる

## タスク
- [ ] 変更した内容をPRDに書く

**Comment by p1ass** [comment]
最後に曲を追加してから24時間経過
↓
セッションをアーカイブする (これで作成者以外はAPIを叩けなくなる)
↓
作成者のUI : 「一定時間セッションが操作されなかったためアーカイブされました。再度このセッションを使いたい場合は、「セッションを再開する」ボタンを押してください」と表示する
参加者のUI : 「セッションがアーカイブされています。セッションを再開したい場合は作成者に連絡をとってください」

てきなUIを表示するってのはどう？

**Comment by dora1998** [comment]
上のUIと、サイドメニューにアーカイブがあれば良さそう。
じゃないと、有効なセッションURLが漏れた時に曲を大量追加されるとアーカイブができないので。

**Comment by sanposhiho** [comment]
セッション作成から24時間でもいいかなって思ったんですけどどうですか？
>最後に曲を追加してから24時間経過

だと悪い人が曲追加し続けたらずっとセッションがARCHIVIEDにならないので、危なそう

**Comment by sanposhiho** [comment]
どら君と危惧してる内容は同じなので最後に曲を追加してから24時間経過+サイドメニューにアーカイブでも🙆‍♂️🙆‍♂️です

**Comment by p1ass** [comment]
> 悪い人が曲追加し続けたらずっとセッションがARCHIVIEDにならないので、危なそう

本当だ、、、
作成から24hで良さそうやね

**Comment by p1ass** [comment]
自主的にアーカイブするのもあって良いと思います！

**Comment by dora1998** [comment]
ただ、作成から24hだと、動いてる状態でアーカイブになる可能性がありそう。
そうすると、まだ再生してるのにリロードしたらアーカイブ状態になって操作できないとかになりそう…？

**Comment by p1ass** [comment]
> ただ、作成から24hだと、動いてる状態でアーカイブになる可能性がありそう。
そうすると、まだ再生してるのにリロードしたらアーカイブ状態になって操作できないとかになりそう…？

Stateが `PLAY` or `PAUSE` なら除外する、とすれば対応できそうだけど、そうすると

> 悪い人が曲追加し続けたらずっとセッションがARCHIVIEDにならないので、危なそう

これで詰むな〜〜〜

**Comment by sanposhiho** [comment]
1日じゃなくて3日とかにして+で手動アーカイブも実装すれば良さそう…？

**Comment by p1ass** [comment]
曲が全部再生し終わったときに、下の方に
`「次の曲を追加する」 「もうセッションを使わないのでアーカイブする」`
みたいなボタンを用意して、ナチュラルにアーカイブしてくれるようなUIにすれば良いんじゃないかな？

UX的にサイドバーからアーカイブをするのはあまりしてくれなさそう

**Comment by sanposhiho** [comment]
アーカイブを手動でうまくやらせるUXにしたとしても一定期間（数日でも一週間でも）で自動アーカイブはしておいた方がいい気もします〜

**Comment by p1ass** [comment]
> セーフネット的な意味合いで一定期間（数日でも一週間でも）で自動アーカイブはしておいた方がいい気もします〜

せやね。3日くらいでいいかな？

**Comment by sanposhiho** [comment]
良さそうだと思います！

**Comment by p1ass** [comment]
@sanposhiho ちなみにこっちはどう？
非同期処理が必要だから今までよりも少し難易度は高し、実装に時間がかかると思うんだけど、さんぽし君なら出来る気がするんだよねw

~(後俺がフロントの手伝いをしたいというのもある)~

**Comment by sanposhiho** [comment]
大丈夫です!! 🚀

**Comment by sanposhiho** [comment]
【雑仕様】

- 手動アーカイブ用の`PUT /sessions/:id/archive`を生やす
  - wsでARCHIVEDのイベントを返す
  - DBのsession.statusをarchivedにする
  - session.statusがarchivedの場合playback、AddQueueなどなどのsessionに関わる操作ができないようにする
- 自動アーカイブ用の`POST /jobs/archive_check`を生やす
  - DBから自動アーカイブする条件に引っかかるsessionのstateを全てarchiveに変更する
  - 利用が少なそうな夜の3時くらい？にcronでAPIを叩く

アーカイブする条件
- session.created_atが3日以上前
- (他になんかありますっけ？)

**Comment by p1ass** [comment]
> 手動アーカイブ用のPUT /sessions/:id/archiveを生やす

良さそう 

> 自動アーカイブ用のPOST /jobs/archive_checkを生やす

どちらかと言うと、jobsというよりbatchでは？
アーカイブするというジョブをまとめて同時に行うので。

> バッチ処理（バッチしょり）とは、コンピュータで1つの流れのプログラム群（ジョブ）を順次に実行すること。あらかじめ定めた処理を一度に行うことを示すコンピュータ用語。

https://ja.wikipedia.org/wiki/%E3%83%90%E3%83%83%E3%83%81%E5%87%A6%E7%90%86

後、 `/archive_check` なんかシンプルじゃないし、 `/archive` で良いんじゃない？w

> 夜の3時くらい

Webサービスのアクセス数が最も減るのは4~5時台なので、その辺にすると良さそう。
具体的な時間は任せます！

>   アーカイブする条件

これはOKそう

**Comment by sanposhiho** [comment]
レビューあざます！！！！！！！諸々了解です👀

**Comment by p1ass** [comment]
あー後セッション作成者だけアーカイブを解除できるようにしないとだ！！

**Comment by sanposhiho** [comment]
> あー後セッション作成者だけアーカイブを解除できるようにしないとだ！！

あ、本当だ完全に考慮忘れしてた
こういう時

- `PUT /sessions/:id/archive`で一括でarchiveに関する操作を行うことにして、リクエストで`archive: true(or false)`みたいな感じで使い分ける
- アーカイブ解除専用の`PUT /sessions/:id/unarchive`を生やす

のどっちがいいですかね…？

**Comment by sanposhiho** [comment]
後、アーカイブから戻したセッションを再びアーカイブにするタイミングなんですけど、

- セッションを復活させてから3日

でいいですかね

**Comment by p1ass** [comment]
> 後、アーカイブから戻したセッションを再びアーカイブにするタイミングなんですけど、
> 
> * セッションを復活させてから3日
> 
> でいいですかね

🙆‍♂️

**Comment by p1ass** [comment]
> * `PUT /sessions/:id/archive`で一括でarchiveに関する操作を行うことにして、リクエストで`archive: true(or false)`みたいな感じにする
> * アーカイブ解除専用の`PUT /sessions/:id/unarchive`を生やす
> 
> のどっちがいいですかね…？

ん〜

PUTは対象のリソースの更新のために使われることと、REST的な思想を考えると、
`PUT /sessions/:id/archive` or `PUT /sessions/:id/status` というエンドポイント１つで `archive: true or false` の両方を行うのが良いかなと思った

 `unarchive` みたな動詞はあまりURIに使うのはよくなさそう (とWebを支える技術に書いてあった気がする)

**Comment by sanposhiho** [comment]
> PUT /sessions/:id/archive or PUT /sessions/:id/status というエンドポイント１つで true or false の両方を行うのが良いかなと思った

~~なるほど`PUT /sessions/:id/status`だとplaybackの領域と被りそうなので、` PUT /sessions/:id/archive `ですかね...~~

って書いてて思ったんですけど/playbackを/statusにrenameして流用してもいいきがしてきたんですけどどう思いますか？
中見てると[ChangePlaybackState](https://github.com/camphor-/relaym-server/blob/master/usecase/session.go#L92)のcase追加するだけですごい簡単にarchiveできそう…？

**Comment by p1ass** [comment]
あ〜確かに 🦀 

変えちゃっていいんじゃない？

**Comment by sanposhiho** [comment]
了解です〜！

**Comment by p1ass** [comment]
後は深夜にバッチを叩くcronを設定する

**Comment by sanposhiho** [comment]
- Rundeckで4じに回るように設定した

**Comment by sanposhiho** [comment]
API自体はうまく動いている

Client側の実装待ちのため、prod用のarchiveのRUNDECKはいったんDISABLEに設定してある

TODO:　prodのarchiveを有効化する

**Comment by sanposhiho** [comment]
Failした時にSlackに通知するようにした

**Comment by sanposhiho** [comment]
prodのARCHIVEのAPIも有効化したのでclose
