### ISSUE TITLE
一部デバイスで再生を検知できない

### ISSUE THREAD

**Issue by dora1998** [camphor-/relaym-server#123]
## 概要

Echo dotで再生時、たまに曲が正常に始まるがRelaym側で再生状態にならない。
再生開始までに他のデバイスより時間がかかるのが原因…？

## 再現方法

1. セッションを作り、曲を適当に追加する
2. Echo dotを再生デバイスとして指定
3. 再生ボタンを押す
4. Relaym側で再生状態にならない(リロードしても同じ)
5. 一曲終わると次が再生されず止まる
6. もう一度再生ボタンを押す
7. 再度1曲目の再生が始まり、Relaym側でも再生状態になる

## ログ

```
```

## 対処方法

- [ ] Task1

**Comment by dora1998** [comment]
1曲目→2曲目でも同様に検知が出来ずに止まる模様？

**Comment by p1ass** [comment]
```
{"time":"2020-06-29T07:59:16.333685272Z","level":"ERROR","prefix":"application","file":"session.go","line":"138","error":"playORResume sessionID=e2990b0d-1a90-4997-a8c4-3855b5a3c250: start to play: call add queue api trackURI=spotify:track:2iGt8kJKM7cUF9TEr50XGF: spotify api: add queue: Restricted device: non-premium user","message":"failed to change playback"}
```

restricted deviceを使おうとすると怒られるので、制限された端末は設定できないようにする。

@dora1998 これフロント側でフィルタリングする？それともサーバでやる？

**Comment by dora1998** [comment]
@p1ass フロント側でやるわ〜

**Comment by dora1998** [comment]
フロント側にissue立てたのでclose
https://github.com/camphor-/relaym-client/issues/234
