### ISSUE TITLE
[Session] INTERRUPTされた後に再度再生を開始すると曲が重複する

### ISSUE THREAD

**Issue by p1ass** [camphor-/relaym-server#125]
## 概要

関連issue #86 

<img src="https://user-images.githubusercontent.com/30015728/86032278-0750df00-ba72-11ea-9cbb-4db8c8bbd1ec.png" width="400px">

<img src="https://user-images.githubusercontent.com/30015728/86032292-0ddf5680-ba72-11ea-8443-14944bc013dd.png" width="400px">

## 再現方法
1. 2曲追加する
1. 再生を開始する
1. 1曲目の途中で、Spotify側で別の曲を再生する
1. Relaymに戻ってページをリロード
1. 同期失敗通知がくる
1. 再度再生ボタンを押す
1. 重複してる😭

## ログ

```
```

## 対処方法

- [ ] Task1

**Comment by p1ass** [comment]
これが原因で何回もデバックすると無限にINTERRUPRが飛んできてた気がする

**Comment by p1ass** [comment]
もしかしたら、再生を開始するタイミングで、Skip APIでキューを全部消化してしまってから、再生APIを叩けば解決出来るかもしれん

https://developer.spotify.com/documentation/web-api/reference-beta/#endpoint-skip-users-playback-to-next-track

@sanposhiho もし暇だったらこの検証やってもらっても良い？

**Comment by sanposhiho** [comment]
おけです、見てみます

**Comment by sanposhiho** [comment]
Skipで飛ばすことはいけそうでした㊗️㊗️
あとは現在「次に再生される曲」に入っている曲数分Skipのapiを叩けば良いのですが、[get-information-about-the-users-current-playback](https://developer.spotify.com/documentation/web-api/reference/player/get-information-about-the-users-current-playback/)とかでは曲数が取れなさそう？ってなっています

**Comment by sanposhiho** [comment]
Skipは次の曲がなくても特にエラーが帰ってくるわけでもない（`NO CONTENT`が出るだけ）のでう〜ん
数十曲も「次に再生される曲」に入れてないだろ、と見て十回Skipを叩く~~素行悪目の~~実装にするって手もありますが…

**Comment by p1ass** [comment]
CurrentlyPlayingInfoがnil か`is_playing : false` なら消化しきったと判定できそう

次の曲がある状態でスキップすると自動で再生されるけど、キューの消化し終わると再生が止まるので。

**Comment by sanposhiho** [comment]
現状「次に再生される曲」に関連するissueが二つある

- Relaym使用前にユーザーが「次に再生される曲」を入れていると順番がおかしくなる #86 
- Relaym使用中にINTERUPTが発生するとユーザーがRelaymを通じて入れていた曲が「次に再生される曲」に入っているため、INTERUPTから再生を再開するときに順番がおかしくなる（本質的には前者と同じ原因） #125 

これに対して「skipで「次に再生される曲」に入っている曲を飛ばす」と言う解決策だと

- Relaym使用前にユーザーが「次に再生」を入れているとそこの曲も全てskipされるまでRelaymの曲が再生されない→時間がかかる
- そもそもskipAPIが少し遅い（雑計測で１曲飛ばすのに0.8秒かかる）ので「次に再生される曲」に多く曲が溜まっていると時間がかかる

と言った問題が発生しました
前者は割と致命的でユーザーが普通にSpotifyを利用していると普通はアルバム単位やプレイリスト単位で音楽を聞いていると思うのでその全曲を飛ばすとなるとかなり時間がかかっちゃうと思います

**Comment by sanposhiho** [comment]
僕的にはあんまりいい対処が思いついてません。やり方が綺麗ではないんですけど以下の方法なら…

Play()は「次に再生」をリセットし、新たな曲の再生を始める（参考: #81 ）ので、

- 一旦ダミーの曲をPlay()する
- その後skip()で「次に再生される曲」を飛ばしていく

をすることで「次に再生」を一括で削除し「次に再生される曲」に入っている曲分だけSkipのAPIを叩けばいい

**Comment by sanposhiho** [comment]
↑「次に再生」=スマホ版だと「再生待ち」のことです、適宜読み替えてください🙇‍♂️（PC版と表示文言が違うっぽい

**Comment by p1ass** [comment]
細かいところまで調べ上げてくれてありがとう :bow:

```
Play()は「次に再生」をリセットし（「次に再生される曲」はリセットしない）、新たな曲の再生を始めると言う動きをするので、これを利用して

- 一旦ダミーの曲をPlay()する
- その後skip()で「次に再生される曲」に元々入っていた曲を飛ばしていく

をすることで「次に再生」を一括で削除し「次に再生される曲」に入っている曲分だけSkipのAPIを叩けばいい
```

俺もこの方法以外はぱっと思いつかないなぁ。
ちなみにこの方法をしたときって、ダミーの曲の音は流れてしまうのかな？


時間がかかる問題は、Skip APIをgoroutineでn並行でコールしたら、全体の処理時間短くならないかな？

**Comment by sanposhiho** [comment]
> ちなみにこの方法をしたときって、ダミーの曲の音は流れてしまうのかな？

おそらく流れないかと（すぐスキップするので）、問題としてはSpotifyに履歴的なものが存在するならそこに変な感じで残っちゃうくらいですかね…🤔

> 時間がかかる問題は、Skip APIをgoroutineでn並行でコールしたら、全体の処理時間短くならないかな？

今は普通にforループで呼び出しているんですけど、なんとなくskipが遅いのは`アプリ→API`の呼び出し自体はさっさと行われてるけどSpotify側の実際の処理が遅いからのような気がしています（for文で一回のループに0.4sかかってるはずがないと思うので…）

↓今の実装

```
	skipOnceTime := 3
	isTracksOnQueue := true
	//TODO: あとで消す
	logger.Infoj(map[string]interface{}{"message": "start loop on skipAllTracks"})
	for i := 1; i <= skipOnceTime && isTracksOnQueue; i++ {
		switch i {
		case skipOnceTime:
			cpi, err := c.CurrentlyPlaying(ctx)
			if err != nil {
				return fmt.Errorf("spotify api: CurrentlyPlaying: %w", err)
			}
			isTracksOnQueue = cpi.Playing
			i = 1

			fallthrough

		default:
			err := cli.NextOpt(opt)
			if convErr := c.convertPlayerError(err); convErr != nil {
				return fmt.Errorf("spotify api: next: %w", convErr)
			}
		}
	}
	//TODO: あとで消す
	logger.Infoj(map[string]interface{}{"message": "finish loop on skipAllTracks"})
```

と言うかこの実装もしかしてすごい数API叩いちゃってる…？（skipの反映がなされるまでfor文の繰り返しの回数分API叩いちゃうので…）

**Comment by sanposhiho** [comment]
>と言うかこの実装もしかしてすごい数API叩いちゃってる…？（skipの反映がなされるまでfor文の繰り返しの回数分API叩いちゃうので…

やばい回数叩いてました（20曲飛ばすために80回叩いてた）
なのでやっぱり
> skipが遅いのはアプリ→APIの呼び出し自体はさっさと行われてるけどSpotify側の実際の処理が遅いから

であっていて
> むしろアプリ側はfor文で一回skip叩くごとに0.3秒sleepとかさせておいた方がいいのかも

ですね

**Comment by p1ass** [comment]
確かにこれはヤバそうw
SkipごとにSleepでも良いけど、CurrentlyPlayingを叩く直前にSleepでも良いかも？

**Comment by sanposhiho** [comment]
- sleepを挟む&ダミー曲再生で頑張る
- ダミー曲はsessionで再生しようとしてるやつを流す
- 曲の追加のタイミングをずらしてRelaymが原因の「次に再生される曲」がいっぱい積まれないようにする
  - 曲の終了時に2曲先の曲を追加する
  - これによりRelaym原因の「次に再生される曲」がMaxで2曲しか積まれなくなる

**Comment by p1ass** [comment]
#126 で解決したのでclose
