### ISSUE TITLE
[Session] セッションやキューを読み書きするリポジトリを実装  

### ISSUE THREAD

**Issue by p1ass** [camphor-/relaym-server#14]
## 概要

セッションやキューを読み書きするリポジトリを実装する。

## 要件
すこし重たいので、テーブル設計とrepositoryの実装でPRを分けたほうが良いです。

- IDを指定してセッションを取得できる
	- 基本情報
	- セッションの作成者
	- 現在の再生状況
-  新規でセッションを作成できる
- キューに曲を追加できる (削除はできなくてよい)

## API仕様
API仕様をみつつ必要なデータベースのカラムを考える。

- https://github.com/camphor-/relaym-server/blob/master/docs/api.md#post-sessions
- https://github.com/camphor-/relaym-server/blob/master/docs/api.md#get-sessionsid

## タスク
- [ ] テーブル設計

**Comment by p1ass** [comment]
これtrack情報を何処までDB側に保存するか悩むな

**Comment by sanposhiho** [comment]
![スクリーンショット 2020-05-05 4 05 58](https://user-images.githubusercontent.com/44139130/81003402-cc716700-8e85-11ea-9926-f06a8f90ff73.png)
一旦テーブル設計のレビューお願いします

**Comment by p1ass** [comment]
-  SMALLINT使ってる部分あるけど、結局アプリケーション側ではint32で扱うのでINTのままでも良いかなぁって思いました！データサイズ削減以外になにか理由ってある？
- あんまり記号の意味が分かってないんだけど、tracksののプライマリキーってuriであってる？もしそうだとすると、「ある曲は一つのセッションにしか属せない」状態になってしまって、このWebサービスを通して1回しかその曲を再生出来ない状況になりそうだなぁと思いました。

**Comment by sanposhiho** [comment]
> データサイズ削減以外になにか理由ってある？
特になかったです

> もしそうだとすると、「ある曲は一つのセッションにしか属せない」状態になってしまって
脳死でuriをPKにしてたんですけど、確かにそうですね…直しておきます

**Comment by sanposhiho** [comment]
> すこし重たいので、テーブル設計とrepositoryの実装でPRを分けたほうが良いです。

っていうのはSQLとrepositoryでそれぞれ別のPR出した方が🙆‍♀️ってことであってますか？

**Comment by p1ass** [comment]
意図としてはリポジトリの実装をしてからテーブル設計のやり直しをすると手戻りが大きいので、途中でレビューを挟みたいという意図だったので、このままテーブル設計をissue側で議論するなら特に分けなくても大丈夫です！🙆‍♂️

**Comment by sanposhiho** [comment]
結局スクショだけだったらわかりにくい部分もあるかなって思ったんでいったんPR出しましたー🙏

**Comment by p1ass** [comment]
一旦終わったのでcloseします。
Thx @sanposhiho ！
