### ISSUE TITLE
次の曲にスキップの機能を実装

### ISSUE THREAD

**Issue by sanposhiho** [camphor-/relaym-server#166]
## 概要
次の曲にスキップするためのAPIを立てる

## 要件
- 次の曲にスキップできる

## タスク
- [x] API仕様かく

**Comment by sanposhiho** [comment]
- `/sessions/:id/next`
- allowToControlByOtherが許可されていない場合、sessionの作成者のみ操作可能
### stateがPLAY
- 次の曲に映る（EventNextTrackが送られる）
- 最後の曲を再生中の場合は再生が止まる（EventStopが送られる）

### stateがPAUSE
- 再生は再開されず、次の曲に移る（EventNextTrackが送られる）
- 最後の曲でpauseだった場合は全ての曲が終わったことになる（EventStopが送られる）

### stateがSTOP
- 次の曲が存在する場合は次の曲に移る（EventNextTrackが送られる）（stateはPAUSEになる）
- 最後の曲でstopだった場合は何も起こらない

### stateがARCHIVED
- APIがエラーを返す（ARCHIVEDの時の操作を許可しない）

**Comment by sanposhiho** [comment]
簡単のために
> 最後の曲でstopだった場合は何も起こらない（STOP→STOP）

を
- 最後の曲でstopだった場合はAPIでエラーを返す（STOP→STOP）

にします

**Comment by p1ass** [comment]
良さそう
タイマー消し忘れだけは気をつけてね

**Comment by sanposhiho** [comment]
実装はマージされてるのでclose
バグあるけど別issue立ってるので
