### ISSUE TITLE
[session] Spotifyにログインしなくてもセッションに参加できるようにする  

### ISSUE THREAD

**Issue by p1ass** [camphor-/relaym-server#46]
## 概要

https://github.com/camphor-/relaym-server/pull/37#discussion_r422262759

利便性の面から、Spotifyにログインしていなくてもセッションに参加できるようにする。

## 要件
- セッションの参加者はSpotifyにログインしていなくてもセッションを見ることができる
	- これは #48 で実装
- セッションの参加者はセッションの作成者のトークンを使って検索を行う
	- これをやる
- セッションの参加者は再生プレイヤーを操作することができる
	- これもセッション作成者のトークンを使って行う

## タスク
- [x] セッション作成者のトークンの有効期限が切れている場合の処理を考える
	- 自分のトークンはミドルウェアで更新されるが、作成者のトークンがこの時点で更新されない場合がある
	- https://github.com/camphor-/relaym-server/blob/master/web/auth_middleware.go#L48

**Comment by p1ass** [comment]
#65 も一緒に直す

**Comment by p1ass** [comment]
@sanposhiho これできそうかな...?

**Comment by sanposhiho** [comment]
👀やります！（土日のCAイベントの勉強で手を付けるの来週以降とかになっちゃいますけど…）

**Comment by sanposhiho** [comment]
[雑に方針]
- session作成時にDBのsessionsにtokenを持たせる
- session参加時にsession（web用語の方）にどのsessionに参加しているかを格納
- AuthMiddlewareで参加しているsessionからtokenを取得する

**Comment by p1ass** [comment]
> - session参加時にセッションにどのsessionに参加しているかを格納
> - AuthMiddlewareで参加しているsessionからtokenを取得する

~これわざわざセッションに入れなくても、URLからsessionって特定できないかな？~

と思ったが、検索APIが使えないのか、、、
検索APIのURLにsession idを含めるのもありだなと思ったんだけどどうだろう？
それとも他にセッションを使う意図ってあるかな？

セッションを使うならこの方法で良いと思います！

**Comment by sanposhiho** [comment]
>検索APIが使えないのか、、、

そうなんですよね
> 検索APIのURLにsession idを含めるのもありだなと思ったんだけどどうだろう

全然思いついてませんでした、なんかそっちの方がスマートな気がしますね
その場合もミドルウェア（Authとは別のミドルウェアにするのが良さそう）でsession idを取得して→…という流れでが良きですかね？（Token使いたいHandler全てでsession idからtoken取って…の処理を入れるのがめんどくさそう）

**Comment by p1ass** [comment]
> なんかそっちの方がスマートな気がしますね

ちょっとRESTの考え方からは外れるけどねw
(元からリソース指向ではないしあまり意識してないけど 😇 )

> その場合もミドルウェア（Authとは別のミドルウェアにするのが良さそう）でsession idを取得して→…という流れでが良きですかね？🤔

良いと思う！ 👍

**Comment by sanposhiho** [comment]
あざます👍👍👍👍
