### ISSUE TITLE
[Auth] オンメモリで持っているログインセッションをMySQLに移行する 

### ISSUE THREAD

**Issue by p1ass** [camphor-/relaym-server#74]
## 概要

仮実装として、ログインセッションをオンメモリで持つ実装をしていたが、これをMySQLで実装する。

なお、ドキュメントでRedisと書いていたが、ミドルウェアが増えると複雑になるのでMySQLに統一する。パフォーマンスが出ないならそのタイミングで移行を検討する

https://github.com/camphor-/relaym-server/blob/master/database/auth.go#L61-L67

## 要件
- ログインセッションが永続化され、サーバを再起動してもセッションが残っている

## タスク
- [ ] Redisを使うと書いてあったドキュメントを削除

**Comment by sanposhiho** [comment]
> Redisを使うと書いてあったドキュメントを削除

はどこのことですか？

**Comment by p1ass** [comment]
@sanposhiho よく探したらここに1行書いてあるだけだったw

https://github.com/camphor-/relaym-server#step3-%E3%83%87%E3%83%BC%E3%82%BF%E3%83%99%E3%83%BC%E3%82%B9%E3%81%AE%E8%A8%AD%E8%A8%88%E3%82%92%E7%90%86%E8%A7%A3%E3%81%99%E3%82%8B

**Comment by sanposhiho** [comment]
あざます！
