### ISSUE TITLE
[Session] Spotifyアプリ側で「[次に聴く]に追加」でキューに曲が詰まれていると、曲順がおかしくなる 

### ISSUE THREAD

**Issue by p1ass** [camphor-/relaym-server#86]
## 概要

1. Spotifyアプリで適当な曲を「[次に聴く]に追加」で「次に再生される曲」に追加 (Tとする)
1. Relaymで(A,B,C)の三曲を追加
1. 再生開始

このとき再生順序が、
A,T,B,Cとなってしまう

## ログ

```
```

## 対処方法

#81 と合わせて良い感じの解決方法を考える必要がありそう

**Comment by p1ass** [comment]
こっちは一旦放置で #81 だけ対応する

**Comment by sanposhiho** [comment]
#126 で†解決†したのでclose
